### ISSUE TITLE
!ready not working

### ISSUE THREAD

**Issue by MrJaroslawo** [KaosDrip/Xensis#26]
Task exception was never retrieved
future: <Task finished name='Task-274' coro=<XMPPClient.event_party_new_captain() done, defined at C:\Users\Jaroosekk\AppData\Local\Programs\Python\Python311\Lib\site-packages\fortnitepy\xmpp.py:1101> exception=KeyError('regionId')>
Traceback (most recent call last):
  File "C:\Users\Jaroosekk\AppData\Local\Programs\Python\Python311\Lib\site-packages\fortnitepy\xmpp.py", line 1125, in event_party_new_captain
    party.update_presence()
  File "C:\Users\Jaroosekk\AppData\Local\Programs\Python\Python311\Lib\site-packages\fortnitepy\party.py", line 3418, in update_presence
    data = self.construct_presence(text=text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jaroosekk\AppData\Local\Programs\Python\Python311\Lib\site-packages\fortnitepy\party.py", line 3409, in construct_presence
    'GamePlaylistName_s': self.meta.playlist_info[0],
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jaroosekk\AppData\Local\Programs\Python\Python311\Lib\site-packages\fortnitepy\party.py", line 1142, in playlist_info
    info['regionId'])
    ~~~~^^^^^^^^^^^^
KeyError: 'regionId'

**Comment by Jaroosekk** [comment]
I updated "fortnitepy" ,the error disappeared but still won't start the game
